apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
        containers:
          - name: mysql-ctr
            image: mysql:latest
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: "admin"
              - name: MYSQL_DATABASE
                value: "mydb"
              - name: MYSQL_USER
                value: "root"
              - name: MYSQL_PASSWORD
                value: "admin"
              - name: MYSQL_DB
                value: "mydb"
            ports:
              - containerPort: 3306
            volumeMounts:
              - name: mysqldata
                mountPath: /var/lib/mysql
            volumes:
              - name: mysqldata
                persistentVolumeClaim:
                  claimName: mysql-pvc
      

